-- Professional scheduling controls and appointment lifecycle.
-- This migration preserves legacy date/time records while making new bookings
-- slot-based, capacity-aware, idempotent, and auditable.

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Africa/Casablanca';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS buffer_minutes INTEGER NOT NULL DEFAULT 0 CHECK (buffer_minutes BETWEEN 0 AND 240);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS minimum_notice_minutes INTEGER NOT NULL DEFAULT 60 CHECK (minimum_notice_minutes BETWEEN 0 AND 43200);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_window_days INTEGER NOT NULL DEFAULT 60 CHECK (booking_window_days BETWEEN 1 AND 365);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS max_bookings_per_day INTEGER CHECK (max_bookings_per_day IS NULL OR max_bookings_per_day >= 1);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancellation_notice_hours INTEGER NOT NULL DEFAULT 24 CHECK (cancellation_notice_hours BETWEEN 0 AND 720);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmation_mode TEXT NOT NULL DEFAULT 'instant' CHECK (confirmation_mode IN ('instant', 'request'));

CREATE TABLE booking_availability_windows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_availability_window_time_range CHECK (end_time > start_time),
  CONSTRAINT booking_availability_window_unique UNIQUE (booking_id, weekday, start_time, end_time)
);

CREATE TABLE booking_date_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_date_override_unique UNIQUE (booking_id, date)
);

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS booking_timezone TEXT NOT NULL DEFAULT 'Africa/Casablanca';
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS guest_count INTEGER NOT NULL DEFAULT 1 CHECK (guest_count >= 1);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS cancelled_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX idx_appointments_idempotency_key
  ON appointments(idempotency_key)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_appointments_provider_schedule
  ON appointments(provider_id, appointment_date, appointment_time, status);
CREATE INDEX idx_appointments_booking_schedule
  ON appointments(booking_id, appointment_date, appointment_time, status);
CREATE INDEX idx_booking_availability_windows_schedule
  ON booking_availability_windows(booking_id, weekday, start_time);
CREATE INDEX idx_booking_date_overrides_schedule
  ON booking_date_overrides(booking_id, date);
