-- FINDit is an independent buyer-request marketplace. Requests and seller
-- offers stay outside the product catalogue. An accepted offer creates a
-- cash-on-delivery order with an immutable financial snapshot.

ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type TEXT NOT NULL DEFAULT 'product';

CREATE TABLE findit_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_number TEXT NOT NULL UNIQUE,
  buyer_id BIGINT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  city TEXT NOT NULL,
  preferred_condition TEXT NOT NULL DEFAULT 'any' CHECK (preferred_condition IN ('any', 'new', 'used')),
  budget_max NUMERIC(14, 2) NOT NULL DEFAULT 0,
  budget_max_minor BIGINT NOT NULL DEFAULT 0 CHECK (budget_max_minor >= 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'accepted', 'cancelled', 'expired')),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE findit_request_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES findit_requests(id) ON DELETE CASCADE,
  media_url TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE findit_offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES findit_requests(id) ON DELETE CASCADE,
  seller_id BIGINT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC(14, 2) NOT NULL,
  price_minor BIGINT NOT NULL CHECK (price_minor > 0),
  delivery_fee NUMERIC(14, 2) NOT NULL DEFAULT 0,
  delivery_fee_minor BIGINT NOT NULL DEFAULT 0 CHECK (delivery_fee_minor >= 0),
  condition TEXT NOT NULL CHECK (condition IN ('new', 'used', 'refurbished')),
  estimated_delivery_days INTEGER NOT NULL CHECK (estimated_delivery_days BETWEEN 1 AND 60),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'withdrawn', 'accepted', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(request_id, seller_id)
);

CREATE TABLE findit_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
  request_id BIGINT NOT NULL REFERENCES findit_requests(id),
  offer_id BIGINT NOT NULL UNIQUE REFERENCES findit_offers(id),
  seller_id BIGINT NOT NULL REFERENCES users(id),
  item_title TEXT NOT NULL,
  item_description TEXT NOT NULL,
  item_condition TEXT NOT NULL,
  price NUMERIC(14, 2) NOT NULL,
  price_minor BIGINT NOT NULL CHECK (price_minor > 0),
  delivery_fee NUMERIC(14, 2) NOT NULL DEFAULT 0,
  delivery_fee_minor BIGINT NOT NULL DEFAULT 0 CHECK (delivery_fee_minor >= 0),
  commission NUMERIC(14, 2) NOT NULL,
  commission_minor BIGINT NOT NULL CHECK (commission_minor >= 0),
  seller_amount NUMERIC(14, 2) NOT NULL,
  seller_amount_minor BIGINT NOT NULL CHECK (seller_amount_minor >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE findit_checkout_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  idempotency_key TEXT NOT NULL,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, idempotency_key)
);

CREATE INDEX idx_findit_requests_catalog ON findit_requests(status, expires_at, created_at DESC);
CREATE INDEX idx_findit_requests_buyer ON findit_requests(buyer_id, created_at DESC);
CREATE INDEX idx_findit_request_media_request ON findit_request_media(request_id, display_order, id);
CREATE INDEX idx_findit_offers_request_status ON findit_offers(request_id, status, created_at DESC);
CREATE INDEX idx_findit_offers_seller ON findit_offers(seller_id, updated_at DESC);
CREATE INDEX idx_findit_orders_seller ON findit_orders(seller_id, order_id);
