-- Provider-neutral COD fulfilment and settlement state. Carrier integration is
-- intentionally not embedded here: a carrier API or imported settlement file
-- must supply the collection and remittance references before seller credit.

CREATE TABLE cod_fulfillments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id),
  seller_id BIGINT NOT NULL REFERENCES users(id),
  source TEXT NOT NULL CHECK(source IN ('product', 'findit')),
  status TEXT NOT NULL DEFAULT 'pending_confirmation'
    CHECK(status IN ('pending_confirmation', 'confirmed', 'shipped', 'delivered', 'refused', 'returned', 'cancelled')),
  settlement_status TEXT NOT NULL DEFAULT 'awaiting_delivery'
    CHECK(settlement_status IN ('awaiting_delivery', 'awaiting_remittance', 'settled', 'void')),
  gross_amount NUMERIC(14, 2) NOT NULL,
  gross_amount_minor BIGINT NOT NULL CHECK(gross_amount_minor >= 0),
  customer_delivery_fee NUMERIC(14, 2) NOT NULL DEFAULT 0,
  customer_delivery_fee_minor BIGINT NOT NULL DEFAULT 0 CHECK(customer_delivery_fee_minor >= 0),
  expected_cod_amount NUMERIC(14, 2) NOT NULL,
  expected_cod_amount_minor BIGINT NOT NULL CHECK(expected_cod_amount_minor >= 0),
  commission NUMERIC(14, 2) NOT NULL,
  commission_minor BIGINT NOT NULL CHECK(commission_minor >= 0),
  seller_amount NUMERIC(14, 2) NOT NULL,
  seller_amount_minor BIGINT NOT NULL CHECK(seller_amount_minor >= 0),
  carrier_name TEXT,
  tracking_number TEXT,
  collected_amount NUMERIC(14, 2),
  collected_amount_minor BIGINT CHECK(collected_amount_minor >= 0),
  carrier_delivery_fee NUMERIC(14, 2),
  carrier_delivery_fee_minor BIGINT CHECK(carrier_delivery_fee_minor >= 0),
  carrier_return_fee NUMERIC(14, 2),
  carrier_return_fee_minor BIGINT CHECK(carrier_return_fee_minor >= 0),
  remitted_amount NUMERIC(14, 2),
  remitted_amount_minor BIGINT CHECK(remitted_amount_minor >= 0),
  carrier_collection_reference TEXT,
  carrier_settlement_reference TEXT,
  collection_note TEXT,
  settlement_note TEXT,
  exception_note TEXT,
  confirmed_at TIMESTAMPTZ,
  dispatched_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  refused_at TIMESTAMPTZ,
  returned_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  settled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(order_id, seller_id)
);

CREATE INDEX idx_cod_fulfillments_seller_status ON cod_fulfillments(seller_id, status, created_at DESC);
CREATE INDEX idx_cod_fulfillments_finance ON cod_fulfillments(settlement_status, status, created_at ASC);
CREATE INDEX idx_cod_fulfillments_order ON cod_fulfillments(order_id, seller_id);
CREATE INDEX idx_cod_fulfillments_tracking ON cod_fulfillments(carrier_name, tracking_number);
CREATE UNIQUE INDEX idx_cod_fulfillments_collection_reference
  ON cod_fulfillments(carrier_collection_reference)
  WHERE carrier_collection_reference IS NOT NULL;
