-- COD disputes intentionally do not change cash, wallet or seller-payout
-- records. They preserve the evidence and decision trail required before a
-- reconciliation controller decides whether a separate financial action is due.
CREATE TABLE order_disputes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fulfillment_id BIGINT NOT NULL REFERENCES cod_fulfillments(id),
  order_id BIGINT NOT NULL REFERENCES orders(id),
  buyer_id BIGINT NOT NULL REFERENCES users(id),
  seller_id BIGINT NOT NULL REFERENCES users(id),
  opened_by BIGINT NOT NULL REFERENCES users(id),
  reason TEXT NOT NULL CHECK(reason IN ('not_received', 'wrong_item', 'damaged', 'not_as_described', 'delivery_issue', 'other')),
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'in_review', 'resolved_buyer', 'resolved_seller', 'return_required', 'closed')),
  resolution TEXT,
  resolved_by BIGINT REFERENCES users(id),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_dispute_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id BIGINT NOT NULL REFERENCES order_disputes(id) ON DELETE CASCADE,
  actor_user_id BIGINT REFERENCES users(id),
  event_type TEXT NOT NULL CHECK(event_type IN ('opened', 'message', 'decision')),
  body TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_disputes_participant
  ON order_disputes(buyer_id, seller_id, updated_at DESC);
CREATE INDEX idx_order_disputes_queue
  ON order_disputes(status, updated_at ASC);
CREATE INDEX idx_order_dispute_events_dispute
  ON order_dispute_events(dispute_id, created_at ASC);
CREATE UNIQUE INDEX idx_order_disputes_one_open_per_fulfillment
  ON order_disputes(fulfillment_id)
  WHERE status IN ('open', 'in_review');
