const EXPECTED_POSTGRES_TABLES = Object.freeze([
  'appointments',
  'audit_logs',
  'auth_sessions',
  'booking_availability_windows',
  'booking_date_overrides',
  'booking_media',
  'booking_slots',
  'bookings',
  'cart',
  'checkout_requests',
  'course_lessons',
  'course_media',
  'courses',
  'digital_files',
  'digital_media',
  'digital_products',
  'digital_purchases',
  'digital_requests',
  'email_logs',
  'email_verifications',
  'enrollments',
  'escrow_transactions',
  'favorites',
  'findit_checkout_requests',
  'findit_offers',
  'findit_orders',
  'findit_request_media',
  'findit_requests',
  'financial_operations',
  'fraud_reports',
  'google_verifications',
  'lesson_progress',
  'messages',
  'order_invoices',
  'order_items',
  'order_status_history',
  'orders',
  'password_resets',
  'payment_splits',
  'payment_transactions',
  'pending_registrations',
  'phone_verification_challenges',
  'product_media',
  'product_offers',
  'product_reviews',
  'products',
  'refund_requests',
  'service_media',
  'service_orders',
  'service_packages',
  'services',
  'users',
  'wallet_ledger_entries',
  'wallet_transactions',
  'wallets',
  'withdrawal_requests',
]);

const REQUIRED_MINOR_UNIT_COLUMNS = Object.freeze([
  ['products', 'price_minor'],
  ['orders', 'total_minor'],
  ['order_items', 'price_minor'],
  ['courses', 'price_minor'],
  ['services', 'price_minor'],
  ['digital_products', 'price_minor'],
  ['bookings', 'price_minor'],
  ['wallets', 'available_balance_minor'],
  ['escrow_transactions', 'amount_minor'],
  ['withdrawal_requests', 'amount_minor'],
  ['wallet_ledger_entries', 'amount_minor'],
  ['payment_transactions', 'amount_minor'],
  ['refund_requests', 'amount_minor'],
  ['findit_requests', 'budget_max_minor'],
  ['findit_offers', 'price_minor'],
  ['findit_offers', 'delivery_fee_minor'],
  ['findit_orders', 'price_minor'],
  ['findit_orders', 'delivery_fee_minor'],
  ['findit_orders', 'commission_minor'],
  ['findit_orders', 'seller_amount_minor'],
]);

module.exports = {
  EXPECTED_POSTGRES_TABLES,
  REQUIRED_MINOR_UNIT_COLUMNS,
};
